on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
	@@ -16,7 +16,7 @@ jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the community :nerd_face:'
	@@ -27,7 +27,7 @@ jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/statistics@main
        if: ${{ github.repository_owner == 'jaidevstudio' }}
        with:
          firebase-key: ${{ secrets.FIREBASE_KEY }}
