on: [push]

jobs:
  table:
    runs-on: ubuntu-latest
    name: Update README from json data
    if: github.repository_owner == 'Jaidevstudio'
    steps:
      - uses: actions/checkout@main
      - name: Read/Write data into README
        uses: EddieHubCommunity/gh-actions-html-table-generator@v0.1
        with:
          json-file-path: "data.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          columns: 3
          object-field-names: '[ "githubUsername", "name", "imageUrl", "issueNumber" ]'
          html-cell: '<td align="center"><p><a href="https://github.com/{{ githubUsername }}">{{ name }}</a></p><img src="{{ imageUrl }}" /><p><a href="https://github.com/Jaidevstudio/Unique-Github-Profiles/issues/{{ issueNumber }}">(💯 give your vote)</a></p></td>'
